"""State definition for the LangGraph-based multi-agent system."""

from typing import TypedDict


class GraphState(TypedDict):
    """Represents the shared state of the multi-agent graph.

    Attributes:
        code: The Python parser code under development or test.
        tests: Pytest test suite generated to evaluate the parser.
        test_output: Captured stdout/stderr from pytest execution.
        iterations: Number of develop-test refinement cycles executed.
        error: Error message or traceback from the last failed test run.
        report: Executive system health report generated by the Analyst node.
        metrics: Computed telemetry metrics from the validated parser run.
    """

    code: str
    tests: str
    test_output: str
    iterations: int
    error: str
    report: str
    metrics: dict
